// <auto-generated />
using System;
using ITHelpDesk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITHelpDesk.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101162612_AddAssetsModels")]
    partial class AddAssetsModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITHelpDesk.Models.AccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessDuration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ITApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ITApprovalName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ITApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ManagerApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerApprovalName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ManagerApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("SecurityApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityApprovalName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SecurityApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SelectedManagerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SelectedManagerId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("AccessRequests", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssetStateId")
                        .HasColumnType("int");

                    b.Property<string>("AssetTag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("NetworkDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WarrantyExpiryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetStateId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("NetworkDetailsId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VendorId");

                    b.ToTable("Assets", (string)null);

                    b.HasDiscriminator<string>("AssetType").HasValue("Asset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.AssetState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssociatedTo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Site")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateComments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("AssetStates", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.ComputerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BiosDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BiosManufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BiosVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SMBiosVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceTag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ComputerInfos", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.HardDisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapacityGB")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HardDisks", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyboardType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Keyboards", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.MemoryDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RAM")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VirtualMemory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MemoryDetails", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.MobileDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailableCapacityGB")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMEI")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModemFirmwareVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TotalCapacityGB")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MobileDetails", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Monitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaxResolution")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MonitorType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Monitors", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Mouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MouseButtons")
                        .HasColumnType("int");

                    b.Property<string>("MouseType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Mice", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.NetworkDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DHCPEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("DHCPServer")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DNSHostname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DefaultGateway")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MACAddress")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("NIC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Network")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NetworkDetails", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.OperatingSystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ServicePack")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystemInfos", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Processor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClockSpeedMHz")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumberOfCores")
                        .HasColumnType("int");

                    b.Property<string>("ProcessorInfo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Processors", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DoorNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Landmark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ITApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ITApprovalName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ITApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ManagerApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerApprovalName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ManagerApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SecurityApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityApprovalName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SecurityApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SelectedManagerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SignatureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SignatureJobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SignatureName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("UsageDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UsageReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SelectedManagerId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("ServiceRequests", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.TicketAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketAttachments", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.TicketLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PerformedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketLogs", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.AccessPoint", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.HasDiscriminator().HasValue("AccessPoint");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Computer", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.Property<int?>("ComputerInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("HardDiskId")
                        .HasColumnType("int");

                    b.Property<int?>("KeyboardId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("MonitorId")
                        .HasColumnType("int");

                    b.Property<int?>("MouseId")
                        .HasColumnType("int");

                    b.Property<int?>("OperatingSystemInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessorId")
                        .HasColumnType("int");

                    b.HasIndex("ComputerInfoId");

                    b.HasIndex("HardDiskId");

                    b.HasIndex("KeyboardId");

                    b.HasIndex("MemoryDetailsId");

                    b.HasIndex("MonitorId");

                    b.HasIndex("MouseId");

                    b.HasIndex("OperatingSystemInfoId");

                    b.HasIndex("ProcessorId");

                    b.HasDiscriminator().HasValue("Computer");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.MobileDevice", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.Property<int?>("MobileDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("OperatingSystemInfoId")
                        .HasColumnType("int");

                    b.HasIndex("MobileDetailsId");

                    b.HasIndex("OperatingSystemInfoId");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("OperatingSystemInfoId")
                                .HasColumnName("MobileDevice_OperatingSystemInfoId");
                        });

                    b.HasDiscriminator().HasValue("MobileDevice");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Printer", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.HasDiscriminator().HasValue("Printer");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Router", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.HasDiscriminator().HasValue("Router");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Server", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.Property<int?>("ComputerInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("HardDiskId")
                        .HasColumnType("int");

                    b.Property<int?>("KeyboardId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("MonitorId")
                        .HasColumnType("int");

                    b.Property<int?>("MouseId")
                        .HasColumnType("int");

                    b.Property<int?>("OperatingSystemInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessorId")
                        .HasColumnType("int");

                    b.HasIndex("ComputerInfoId");

                    b.HasIndex("HardDiskId");

                    b.HasIndex("KeyboardId");

                    b.HasIndex("MemoryDetailsId");

                    b.HasIndex("MonitorId");

                    b.HasIndex("MouseId");

                    b.HasIndex("OperatingSystemInfoId");

                    b.HasIndex("ProcessorId");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("ComputerInfoId")
                                .HasColumnName("Server_ComputerInfoId");

                            t.Property("HardDiskId")
                                .HasColumnName("Server_HardDiskId");

                            t.Property("KeyboardId")
                                .HasColumnName("Server_KeyboardId");

                            t.Property("MemoryDetailsId")
                                .HasColumnName("Server_MemoryDetailsId");

                            t.Property("MonitorId")
                                .HasColumnName("Server_MonitorId");

                            t.Property("MouseId")
                                .HasColumnName("Server_MouseId");

                            t.Property("OperatingSystemInfoId")
                                .HasColumnName("Server_OperatingSystemInfoId");

                            t.Property("ProcessorId")
                                .HasColumnName("Server_ProcessorId");
                        });

                    b.HasDiscriminator().HasValue("Server");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Switch", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.HasDiscriminator().HasValue("Switch");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.VirtualHost", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.Property<int?>("ComputerInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("HardDiskId")
                        .HasColumnType("int");

                    b.Property<int?>("KeyboardId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("MonitorId")
                        .HasColumnType("int");

                    b.Property<int?>("MouseId")
                        .HasColumnType("int");

                    b.Property<int?>("OperatingSystemInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessorId")
                        .HasColumnType("int");

                    b.Property<string>("VMPlatform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("ComputerInfoId");

                    b.HasIndex("HardDiskId");

                    b.HasIndex("KeyboardId");

                    b.HasIndex("MemoryDetailsId");

                    b.HasIndex("MonitorId");

                    b.HasIndex("MouseId");

                    b.HasIndex("OperatingSystemInfoId");

                    b.HasIndex("ProcessorId");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("ComputerInfoId")
                                .HasColumnName("VirtualHost_ComputerInfoId");

                            t.Property("HardDiskId")
                                .HasColumnName("VirtualHost_HardDiskId");

                            t.Property("KeyboardId")
                                .HasColumnName("VirtualHost_KeyboardId");

                            t.Property("MemoryDetailsId")
                                .HasColumnName("VirtualHost_MemoryDetailsId");

                            t.Property("MonitorId")
                                .HasColumnName("VirtualHost_MonitorId");

                            t.Property("MouseId")
                                .HasColumnName("VirtualHost_MouseId");

                            t.Property("OperatingSystemInfoId")
                                .HasColumnName("VirtualHost_OperatingSystemInfoId");

                            t.Property("ProcessorId")
                                .HasColumnName("VirtualHost_ProcessorId");
                        });

                    b.HasDiscriminator().HasValue("VirtualHost");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.VirtualMachine", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.Property<int?>("ComputerInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("HardDiskId")
                        .HasColumnType("int");

                    b.Property<int?>("KeyboardId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("MonitorId")
                        .HasColumnType("int");

                    b.Property<int?>("MouseId")
                        .HasColumnType("int");

                    b.Property<int?>("OperatingSystemInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessorId")
                        .HasColumnType("int");

                    b.Property<int>("VirtualHostId")
                        .HasColumnType("int");

                    b.HasIndex("ComputerInfoId");

                    b.HasIndex("HardDiskId");

                    b.HasIndex("KeyboardId");

                    b.HasIndex("MemoryDetailsId");

                    b.HasIndex("MonitorId");

                    b.HasIndex("MouseId");

                    b.HasIndex("OperatingSystemInfoId");

                    b.HasIndex("ProcessorId");

                    b.HasIndex("VirtualHostId");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("ComputerInfoId")
                                .HasColumnName("VirtualMachine_ComputerInfoId");

                            t.Property("HardDiskId")
                                .HasColumnName("VirtualMachine_HardDiskId");

                            t.Property("KeyboardId")
                                .HasColumnName("VirtualMachine_KeyboardId");

                            t.Property("MemoryDetailsId")
                                .HasColumnName("VirtualMachine_MemoryDetailsId");

                            t.Property("MonitorId")
                                .HasColumnName("VirtualMachine_MonitorId");

                            t.Property("MouseId")
                                .HasColumnName("VirtualMachine_MouseId");

                            t.Property("OperatingSystemInfoId")
                                .HasColumnName("VirtualMachine_OperatingSystemInfoId");

                            t.Property("ProcessorId")
                                .HasColumnName("VirtualMachine_ProcessorId");
                        });

                    b.HasDiscriminator().HasValue("VirtualMachine");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Workstation", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Asset");

                    b.Property<int?>("ComputerInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("HardDiskId")
                        .HasColumnType("int");

                    b.Property<int?>("KeyboardId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("MonitorId")
                        .HasColumnType("int");

                    b.Property<int?>("MouseId")
                        .HasColumnType("int");

                    b.Property<int?>("OperatingSystemInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessorId")
                        .HasColumnType("int");

                    b.HasIndex("ComputerInfoId");

                    b.HasIndex("HardDiskId");

                    b.HasIndex("KeyboardId");

                    b.HasIndex("MemoryDetailsId");

                    b.HasIndex("MonitorId");

                    b.HasIndex("MouseId");

                    b.HasIndex("OperatingSystemInfoId");

                    b.HasIndex("ProcessorId");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("ComputerInfoId")
                                .HasColumnName("Workstation_ComputerInfoId");

                            t.Property("HardDiskId")
                                .HasColumnName("Workstation_HardDiskId");

                            t.Property("KeyboardId")
                                .HasColumnName("Workstation_KeyboardId");

                            t.Property("MemoryDetailsId")
                                .HasColumnName("Workstation_MemoryDetailsId");

                            t.Property("MonitorId")
                                .HasColumnName("Workstation_MonitorId");

                            t.Property("MouseId")
                                .HasColumnName("Workstation_MouseId");

                            t.Property("OperatingSystemInfoId")
                                .HasColumnName("Workstation_OperatingSystemInfoId");

                            t.Property("ProcessorId")
                                .HasColumnName("Workstation_ProcessorId");
                        });

                    b.HasDiscriminator().HasValue("Workstation");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Smartphone", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.MobileDevice");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("OperatingSystemInfoId")
                                .HasColumnName("MobileDevice_OperatingSystemInfoId");
                        });

                    b.HasDiscriminator().HasValue("Smartphone");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Tablet", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.MobileDevice");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("OperatingSystemInfoId")
                                .HasColumnName("MobileDevice_OperatingSystemInfoId");
                        });

                    b.HasDiscriminator().HasValue("Tablet");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.CiscoRouter", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Router");

                    b.HasDiscriminator().HasValue("CiscoRouter");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.CiscoCatosSwitch", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Switch");

                    b.HasDiscriminator().HasValue("CiscoCatosSwitch");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.CiscoSwitch", b =>
                {
                    b.HasBaseType("ITHelpDesk.Models.Assets.Switch");

                    b.HasDiscriminator().HasValue("CiscoSwitch");
                });

            modelBuilder.Entity("ITHelpDesk.Models.AccessRequest", b =>
                {
                    b.HasOne("ITHelpDesk.Models.ApplicationUser", "SelectedManager")
                        .WithMany()
                        .HasForeignKey("SelectedManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITHelpDesk.Models.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("ITHelpDesk.Models.AccessRequest", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectedManager");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Asset", b =>
                {
                    b.HasOne("ITHelpDesk.Models.Assets.AssetState", "AssetState")
                        .WithMany()
                        .HasForeignKey("AssetStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ITHelpDesk.Models.Assets.NetworkDetails", "NetworkDetails")
                        .WithMany()
                        .HasForeignKey("NetworkDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITHelpDesk.Models.Assets.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssetState");

                    b.Navigation("CreatedBy");

                    b.Navigation("NetworkDetails");

                    b.Navigation("Product");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ITHelpDesk.Models.ServiceRequest", b =>
                {
                    b.HasOne("ITHelpDesk.Models.ApplicationUser", "SelectedManager")
                        .WithMany()
                        .HasForeignKey("SelectedManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITHelpDesk.Models.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("ITHelpDesk.Models.ServiceRequest", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectedManager");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Ticket", b =>
                {
                    b.HasOne("ITHelpDesk.Models.ApplicationUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ITHelpDesk.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ITHelpDesk.Models.TicketAttachment", b =>
                {
                    b.HasOne("ITHelpDesk.Models.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ITHelpDesk.Models.TicketLog", b =>
                {
                    b.HasOne("ITHelpDesk.Models.ApplicationUser", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITHelpDesk.Models.Ticket", "Ticket")
                        .WithMany("Logs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedBy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ITHelpDesk.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ITHelpDesk.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITHelpDesk.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ITHelpDesk.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Computer", b =>
                {
                    b.HasOne("ITHelpDesk.Models.Assets.ComputerInfo", "ComputerInfo")
                        .WithMany()
                        .HasForeignKey("ComputerInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.HardDisk", "HardDisk")
                        .WithMany()
                        .HasForeignKey("HardDiskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Keyboard", "Keyboard")
                        .WithMany()
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.MemoryDetails", "MemoryDetails")
                        .WithMany()
                        .HasForeignKey("MemoryDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Mouse", "Mouse")
                        .WithMany()
                        .HasForeignKey("MouseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.OperatingSystemInfo", "OperatingSystemInfo")
                        .WithMany()
                        .HasForeignKey("OperatingSystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ComputerInfo");

                    b.Navigation("HardDisk");

                    b.Navigation("Keyboard");

                    b.Navigation("MemoryDetails");

                    b.Navigation("Monitor");

                    b.Navigation("Mouse");

                    b.Navigation("OperatingSystemInfo");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.MobileDevice", b =>
                {
                    b.HasOne("ITHelpDesk.Models.Assets.MobileDetails", "MobileDetails")
                        .WithMany()
                        .HasForeignKey("MobileDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.OperatingSystemInfo", "OperatingSystemInfo")
                        .WithMany()
                        .HasForeignKey("OperatingSystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MobileDetails");

                    b.Navigation("OperatingSystemInfo");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Server", b =>
                {
                    b.HasOne("ITHelpDesk.Models.Assets.ComputerInfo", "ComputerInfo")
                        .WithMany()
                        .HasForeignKey("ComputerInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.HardDisk", "HardDisk")
                        .WithMany()
                        .HasForeignKey("HardDiskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Keyboard", "Keyboard")
                        .WithMany()
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.MemoryDetails", "MemoryDetails")
                        .WithMany()
                        .HasForeignKey("MemoryDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Mouse", "Mouse")
                        .WithMany()
                        .HasForeignKey("MouseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.OperatingSystemInfo", "OperatingSystemInfo")
                        .WithMany()
                        .HasForeignKey("OperatingSystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ComputerInfo");

                    b.Navigation("HardDisk");

                    b.Navigation("Keyboard");

                    b.Navigation("MemoryDetails");

                    b.Navigation("Monitor");

                    b.Navigation("Mouse");

                    b.Navigation("OperatingSystemInfo");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.VirtualHost", b =>
                {
                    b.HasOne("ITHelpDesk.Models.Assets.ComputerInfo", "ComputerInfo")
                        .WithMany()
                        .HasForeignKey("ComputerInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.HardDisk", "HardDisk")
                        .WithMany()
                        .HasForeignKey("HardDiskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Keyboard", "Keyboard")
                        .WithMany()
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.MemoryDetails", "MemoryDetails")
                        .WithMany()
                        .HasForeignKey("MemoryDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Mouse", "Mouse")
                        .WithMany()
                        .HasForeignKey("MouseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.OperatingSystemInfo", "OperatingSystemInfo")
                        .WithMany()
                        .HasForeignKey("OperatingSystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ComputerInfo");

                    b.Navigation("HardDisk");

                    b.Navigation("Keyboard");

                    b.Navigation("MemoryDetails");

                    b.Navigation("Monitor");

                    b.Navigation("Mouse");

                    b.Navigation("OperatingSystemInfo");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.VirtualMachine", b =>
                {
                    b.HasOne("ITHelpDesk.Models.Assets.ComputerInfo", "ComputerInfo")
                        .WithMany()
                        .HasForeignKey("ComputerInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.HardDisk", "HardDisk")
                        .WithMany()
                        .HasForeignKey("HardDiskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Keyboard", "Keyboard")
                        .WithMany()
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.MemoryDetails", "MemoryDetails")
                        .WithMany()
                        .HasForeignKey("MemoryDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Mouse", "Mouse")
                        .WithMany()
                        .HasForeignKey("MouseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.OperatingSystemInfo", "OperatingSystemInfo")
                        .WithMany()
                        .HasForeignKey("OperatingSystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.VirtualHost", "VirtualHost")
                        .WithMany()
                        .HasForeignKey("VirtualHostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComputerInfo");

                    b.Navigation("HardDisk");

                    b.Navigation("Keyboard");

                    b.Navigation("MemoryDetails");

                    b.Navigation("Monitor");

                    b.Navigation("Mouse");

                    b.Navigation("OperatingSystemInfo");

                    b.Navigation("Processor");

                    b.Navigation("VirtualHost");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Assets.Workstation", b =>
                {
                    b.HasOne("ITHelpDesk.Models.Assets.ComputerInfo", "ComputerInfo")
                        .WithMany()
                        .HasForeignKey("ComputerInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.HardDisk", "HardDisk")
                        .WithMany()
                        .HasForeignKey("HardDiskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Keyboard", "Keyboard")
                        .WithMany()
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.MemoryDetails", "MemoryDetails")
                        .WithMany()
                        .HasForeignKey("MemoryDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Mouse", "Mouse")
                        .WithMany()
                        .HasForeignKey("MouseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.OperatingSystemInfo", "OperatingSystemInfo")
                        .WithMany()
                        .HasForeignKey("OperatingSystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITHelpDesk.Models.Assets.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ComputerInfo");

                    b.Navigation("HardDisk");

                    b.Navigation("Keyboard");

                    b.Navigation("MemoryDetails");

                    b.Navigation("Monitor");

                    b.Navigation("Mouse");

                    b.Navigation("OperatingSystemInfo");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("ITHelpDesk.Models.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
